### ISSUE TITLE
pipes ignored in @effection/node `exec`

### ISSUE THREAD

**Issue by jbolda** [thefrontside/effection#266]
When using `exec`, we would expect it to operate as a shell and properly consider piped commands. Passing it a string that contains a pipe effectively ignores the pipe. See below for a minimal reproduction.

In `main.js`:
```js
import effection from "effection";
import { main, exec } from "@effection/node";

const sh = function* (command, options, log) {
  // @ts-ignore
  let child = yield exec(command, options);
  if (log !== false) {
    // @ts-ignore
    yield effection.spawn(
      child.stdout.subscribe().forEach(function* (datum) {
        const out = datum.toString().trim();
        if (out !== "") console.log(out);
      })
    );

    // @ts-ignore
    yield effection.spawn(
      child.stderr.subscribe().forEach(function* (datum) {
        const out = datum.toString().trim();
        if (out !== "") console.error(out);
      })
    );
  }

  const out = yield child.expect();
  // @ts-ignore
  const stripped = Buffer.concat(out.tail).toString().trim();
  return stripped;
};

main(function* start() {
  // this is the most simple display of the issue I can think of
  yield sh('echo "should not echo" | echo "this should echo instead"'); // we expect: this should echo instead
  // this is the first part of the "real" command we want to use
  yield sh("cargo search wry --limit 1");
  // adding in the pipe, it errors out because `cargo search` finds the `-n` within the `sed` command
  yield sh('cargo search wry --limit 1 | sed -nE \'s/^[^"]*"//; s/".*//1p\' -');
});

```

In `package.json`:
```json
{
  "name": "test-ctrlc",
  "version": "0.0.0",
  "main": "index.js",
  "type": "module",
  "license": "MIT",
  "dependencies": {
    "@effection/node": "1.0.1",
    "effection": "1.0.0"
  }
}
```

When run with `node main.js` (with node@v14.16.0), the following stdout is produced:
```shell
❯ node main.js
should not echo | echo this should echo instead
wry = "0.6.0"    # Cross-platform WebView rendering library
... and 3 crates more (use --limit N to see more)
error: Found argument '-n' which wasn't expected, or isn't valid in this context

USAGE:
    cargo.exe search --limit <LIMIT>

For more information try --help
Error [ExecError]: code: 1
env: {}
$ cargo search wry --limit 1 | sed -nE s/^[^"]*"//; s/".*//1p -
error: Found argument '-n' which wasn't expected, or isn't valid in this context

USAGE:
    cargo.exe search --limit <LIMIT>

For more information try --help

    at Object.expect (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\@effection\node\dist\node.cjs.devel
opment.js:255:19)
    at expect.next (<anonymous>)
    at C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:8145
    at e.r.advance (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:7781)
    at e.r.trapExit (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:8107)
    at t.n.finalize (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:5618)
    at t.n.resume (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:4972)
    at e.r.advance (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:7827)
    at e.r.trapExit (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:8107)
    at t.n.finalize (C:\Users\Jacob\Documents\dev\frontside\test-ctrlc\node_modules\effection\dist\effection.js:1:5618)
```

**Comment by cowboyd** [comment]
It' a bummer because it apperas that shellwords parses the `I` as just another argument:

https://runkit.com/cowboyd/shellwords-does-not-work-with-pipe

I think we may not be able to avoid spawning a separate shell. I can't remember why we didn't. Was it because it spawned another window on Windows?

<blockquote><div><strong><a href="https://runkit.com/cowboyd/shellwords-does-not-work-with-pipe">RunKit</a></strong></div><div>RunKit notebooks are interactive javascript playgrounds connected to a complete node environment right in your browser. Every npm module pre-installed.</div></blockquote>

**Comment by jnicklas** [comment]
I have a vague memory that this was to make it possible to forward signals to the child process? The shell between the processes prevents that. Also there were problems in windows. I think we should allow `shell: true` and if it is enabled we should not try and parse the command using shellwords. IMO that would be preferable to using a shell by default.
